### ISSUE TITLE
Introduce missing topics

### ISSUE THREAD

**Issue by stefanobaghino** [js-girls/workshop#10]
We overlooked some topics while delivering the first course, for example we haven't explained what the DOM is and how JavaScript interacts with it. We should identify relevant topics like this that haven't been covered so far but that are important for an introductory course and make sure they find their way into the next iteration.

The work made to solve this issue will complement that done to solve #9.

**Comment by Granze** [comment]
This is crucial for the level 0. I've added [this page](https://github.com/js-girls/workshop/blob/master/docs/level0/00-step0.md) that should be filled with examples and link to relevant resources.
I'll put this on high priority after we finish the level 1 documentation.
