### ISSUE TITLE
Firebase URL should be a variable

### ISSUE THREAD

**Issue by Granze** [js-girls/workshop#13]
The Firebase URL is now hardcoded in the `fetch` function. It should be extracted and assigned to a variable.
Maybe we can put it in the [utils.js](https://github.com/js-girls/workshop/blob/master/level-01/utils/utils.js) file?

The new URL should be `https://jsgirls-level1.firebaseio.com/`

**Important** the documentation should be modified accordingly.

**Comment by zanza00** [comment]
Moved to utils.js using a dandy `const FIREBASE_JSON`

**Comment by Granze** [comment]
`const` only works in strict mode in Chrome and NOT in strict mode in Safari, so I renamed it to `var`
