### ISSUE TITLE
Setup the new Firebase app

### ISSUE THREAD

**Issue by Granze** [js-girls/workshop#26]
https://jsgirls-level1.firebaseio.com/

**Comment by danielegallingani** [comment]
added [server validation rules ](https://jsgirls-level1.firebaseio.com/?page=Security) requiring:
- `title` field to exists and to be longer than 1 char
- `body` field to exists and to be longer than 1 char

beware: any field can be set in the request body, it will just be stored (this might be useful for storing timestamps in extra levels)
